const observePositions: string[] = [
	'Hauptstiege OG1',
	'Hauptstiege Mezzanin 2',
	'OG2 Bibliothek',
	'Hauptstiege OG2',
	'Kleine Stiege OG2',
	'Kleine Stiege Mezzanin 2',
	'SX Meetingraum',
	'Kleine Stiege Mezzanin 1',
	'kleiner Gang EG',
	'Kleine Stiege Keller',
	'langer Gang Keller',
	'kleiner Gang Keller',
	'Hauptstiege Keller',
	'Hauptstiege EG',
	'Hauptstiege Mezzanin 1',
	'Büro 711',
	'Büro 712',
	'Büro 713',
	'Büro 714',
	'Büro 715',
	'Büro 716',
	'Büro 717',
	'Büro 718',
	'Büro 719',
	'Büro 720',
	'Büro 721',
	'Büro 722',
	'Büro 723',
	'Büro 724',
	'Büro 724',
];

export { observePositions };
